# ワークフロー名
name: scraping_bot
on:
  #push:
  #schedule:
  # 定期実行する時間
  - cron: "0 12 * * *"

permissions:
  contents: write # リポジトリのコンテンツに書き込み権限を付与

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          # 定期実行するファイルを指定
          python scraping/scraping_test.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add DB/room_test.db
          git commit -m 'Update database with latest scraped data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
